# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so
version: 0.1

# Exclude
exclude: [vendor]

# Permalinks
permalink:        pretty

# Setup
title:            'karthik-vv'
tagline:          '.github.io'
description:      'Software Engineer @ Practo'
url:              https://karthik-vv.github.io
baseurl:          ''
paginate:         5
paginate_path:    '/page:num/'

author:
  name: 'Karthik VV'
  email: 'karthikvv2693[at]gmail[dot]com'
  github: karthik-vv
  facebook: vvkarthik.alien
  linkedin: shams-sheikh-20328154
  linkedin_link: 'https://www.linkedin.com/in/shams-sheikh-20328154'
  kaggle_link: 'https://www.kaggle.com/shamssam'
  # goodreads: pesteadman
  # orcid: http://orcid.org/0000-0002-5814-4977
  # google_scholar: http://scholar.google.ca/citations?user=Xrn76pEAAAAJ
  email_md5: 3D7BFA8AACC328035A60BE82F1D93A97
  emailalt_md5: 3D7BFA8AACC328035A60BE82F1D93A97
  disqus_shortname: shams-sam
  # google_analytics_id: UA-27104497-1
  # google_analytics_url: 
  bio: Software Engineer @ Practo

github:
  repo: karthik-vv/karthik-vv.github.io
